### ISSUE TITLE
Docker image crystallang/crystal:1.0.0 uses bintray, so apt update doesn't work and the image cannot be extended

### ISSUE THREAD

**Issue by daliborfilus** [crystal-lang/crystal-dist#11]
I don't know if this is the right place to create this issue, so please feel free to redirect me.

Current https://hub.docker.com/r/crystallang/crystal/ crystallang/crystal:1.0.0 image uses bintray, so if I need to add something to it, I cannot (easily) do so.

```
 => CACHED [build  1/18] FROM docker.io/crystallang/crystal:1.0.0                                                                 0.0s
 => ERROR [build  2/18] RUN apt-get update && apt-get install -y time && rm -rf /var/lib/apt/lists/*                              2.4s
------             
...
#9 1.633 Get:19 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1413 kB]
#9 1.770 Reading package lists...
#9 2.405 E: Failed to fetch https://dl.bintray.com/crystal/deb/dists/all/InRelease  403  Forbidden [IP: 3.127.93.119 443]
#9 2.405 E: The repository 'https://dl.bintray.com/crystal/deb all InRelease' is not signed.
------
executor failed running [/bin/sh -c apt-get update && apt-get install -y time && rm -rf /var/lib/apt/lists/*]: exit code: 100
```

Can you please update the image without using bintray? (If there is one already, I cannot see it.)
Perhaps the build process could copy the .deb and install it locally - or better yet, just build the docker image based on debian in a multistage build, without building the .deb externally first? Then it would not be dependent on ANY external source repositories, except debian's and would prevent other such issues in the future?

Current workaround for me is to create my own crystal:1.0.0 image (based on OBS repository, or build my own crystal), OR remove the old repositories during the docker build process and replace them with OBS, but that would be a temporary solution, requiring me to change it when the crystal:1.0.0 changes (I would have a dependency on your build process in my build process, which is worse than having to build my own crystal).

**Comment by straight-shoota** [comment]
The current image should not include any references to the bintray repositories since https://github.com/crystal-lang/crystal/issues/10678. Please pull the latest image from dockerhub (`docker pull crystallang/crystal:1.0.0`).

**Comment by daliborfilus** [comment]
Well... that is embarrassing. I thought I did. Thank you!
